name: Build and Deploy the application
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: kundankkkrishna/newapp:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      - name: Pull Docker image
        run: docker pull docker.io/kundankkkrishna/newapp:latest
        
      - name: check minikube status
        run: minikube status
        
      - name: setup-minikube
        uses: medyagh/setup-minikube@v0.0.13
        with:
          context: .
    
      - name: check cluster
        run: |
          kubectl get pods,services,deployments
        
      - name: Deploy to minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          kubectl apply -f alldeployments.yml
        
      - name: Test service URLs
        run: |
            minikube service list
            minikube service myservice --url
