name: Build and Deploy the application
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kundankkkrishna/newapp:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
      
      - name: Log in to Docker registry
        run: docker login docker.io -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      - name: Pull Docker image
        run: docker pull docker.io/kundankkkrishna/newapp:latest
        
      - name: setup-minikube
        uses: medyagh/setup-minikube@v0.0.13
        with:
          context: .
      
      - name: find current directory
        run: pwd
      - name: test file location
        run: |
            declare deployment_file_path
            deployment_file_path=$(sudo find ../ -name alldeployments.yml)
            echo $deployment_file_path
            id
            sudo -s cd /var/lib/docker/overlay2/e03d87ef1250957fb7f2b9bb41e307d104b87de3aac9f51f5c5b75ef636e8c93/diff/usr/src/path/
            sudo -s pwd
        
      - name: Deploy to minikube
        run: kubectl apply -f $deployment_file_path
        
      - name: Test service URLs
        run: |
            minikube service list
            minikube service myservice --url
