name: Deploy to server

on:
  push:
    branches:
      - main
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  

      - name: Deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.233.244.159 "docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD docker.io/kundankkkrishna/finalapp" -c "docker pull kundankkkrishna/finalapp:latest:" \
          ssh -o StrictHostKeyChecking=no ubuntu@13.233.244.159 "docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD docker.io/kundankkkrishna/finalapp" -c "docker run -d -p 8081:8081 kundankkkrishna/finalapp:latest"
