name: Docker Build and Deploy
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  USERNAME: ${{ secrets.USER_NAME }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -qq openssh-client

      - name: Set up SSH key
        run: echo $SSH_KEY > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server via SSH
        
        run: |
          # Install AWS CLI (if necessary)
          # sudo apt-get install -qq awscli


          # connect to the server and run Docker commands
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$SERVER_IP << 'EOF'

          # Pull the latest image from Docker Hub
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          docker pull kundankkkrishna/finalapp:latest

          # Stop and remove the existing container
          docker stop appcontainer || true
          docker rm appcontainer || true

          # Run the new container
          docker run -d --name appcontainer -p 80:80 kundankkkrishna/finalapp:latest
          '
