name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy Docker container
        run: |
          # Replace the placeholders below with your actual deployment commands.
           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@65.0.18.62 "sudo docker pull kundankkkrishna/finalapp:latest"
           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@65.0.18.62 "sudo docker run -d -p 8081:8081 finalapp:latest"
