name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Log in to Docker Hub
        run: docker login -u kundankkkrishna -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy Docker container
        run: |
          # Replace the placeholders below with your actual deployment commands.
            ssh -o StrictHostKeyChecking=no ubuntu@13.233.244.159 "sudo docker pull kundankkkrishna/finalapp:latest"
            ssh -o StrictHostKeyChecking=no ubuntu@13.233.244.159 "sudo docker run -d -p 8081:8081 finalapp:latest"
