name: mynodeappworkflow
on: push
env:
  TAG: ${{ github.sha }}
  NAMESPACE: kundankkkrishna
  REGISTRY_HOSTNAME: docker.io
  IMAGE_NAME: newapp
  CLUSTER: minikube
  DEPLOYMENT_NAME: NodeappActionsDeployment
  PORT: 5001
  IMAGE_ADDRESS: ${ $REGISTRY_HOSTNAME/$NAMESPACE/$IMAGE_NAME :$TAG }

jobs:
  Deploymentjob:
    name: Deployment
    runs-on: self-hosted
    environment: demo
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Build the Docker image
    - name: Build with Docker
      run: |
        docker build . -t $IMAGE_ADDRESS
  
    # Push the image to dockerhub repository
    - name: Push the image to Dockerhub repository
      run: |
        docker push $IMAGE_ADDRESS

    # Deploy the Docker image to the cluster
    - name: Deploy to cluster
      run: |
        kubectl config current-context
        kubectl create deployment $DEPLOYMENT_NAME --image= $IMAGE_ADDRESS -o yaml > deployment.yaml
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
        kubectl apply -f service.yaml
        kubectl get services -o wide
