name: mynodeappworkflow
on: push
env:
  GITHUB_SHA: ${{ github.sha }}
  NAMESPACE: kundankkkrishna
  REGISTRY_HOSTNAME: docker.io
  IMAGE_NAME: finalapp
  CLUSTER: minikube
  DEPLOYMENT_NAME: NodeappActionsDeployment
  PORT: 5001

jobs:
  Deploymentjob:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Build the Docker image
    - name: Build with Docker
      run: |
        docker build -t "$REGISTRY_HOSTNAME"/"$NAMESPACE"/"$IMAGE_NAME":"$GITHUB_SHA"
  
    # Push the image to dockerhub repository
    - name: Push the image to Dockerhub repository
      run: |
        docker push $REGISTRY_HOSTNAME/$NAMESPACE/$IMAGE_NAME:$GITHUB_SHA

    # Deploy the Docker image to the cluster
    - name: Deploy to cluster
      run: |
        ibmcloud ks cluster config --cluster $CLUSTER
        kubectl config current-context
        kubectl create deployment $DEPLOYMENT_NAME --image=$REGISTRY_HOSTNAME/$NAMESPACE/$IMAGE_NAME:$GITHUB_SHA --dry-run -o yaml > deployment.yaml
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
        kubectl apply -f service.yaml
        kubectl get services -o wide
