name: Build and Deploy the application
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: setup and deploy
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: kubectl
        run: kubectl get pods -A
      - name: Build image
        run: docker build -f ./Dockerfile -t kundankkkrishna/nodeapp:latest
      - name: Push the image
        run: docker push kundankkkrishna/nodeapp:latest
      - name: Deploy to cluster
        run: kubectl apply -f kube
      - name: Accessing the service
        run: |
            minikube service list
            minikube service nodeservice --url
            echo "launching the service"
            curl $(minikube service nodeservice --url )
